data_cfg:
  dataset_name: CASIA-B
  dataset_root: ''
  dataset_partition: .
  num_workers: 1
  remove_no_gallery: false 
  test_dataset_name: CASIA-B

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 60000
  save_name: GaitBase_DA
  sampler:
Other options:   fixed_unordered

    batch_size:
      - 4 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30
    frames_num_max: 40
    frames_num_min: 20
    frames_skip_num: 2
    sample_type:  fixed_ordered #fixed_unordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  metric: euc # cos
  transform:
    - type: BaseSilCuttingTransform
      cutting: 10


model_cfg:
  SeparateFCs:
    in_channels: 256   
    out_channels: 256
    parts_num:   32   
  SeparateBNNecks:
    class_num: 74
    in_channels: 256
    parts_num: 32  
  bin_num:  
    - 32  #16


trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: false
  log_iter: 100
  restore_ckpt_strict: true
  restore_hint: 0
  sampler:
    batch_shuffle: true
    batch_size:
      - 4 # TripletSampler, batch_size[0] indicates Number of Identity
      - 6 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    frames_num_max: 40 # max frames number for unfixed training
    frames_num_min: 20 # min frames number for unfixed traing
    frames_skip_num: 2
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    type: TripletSampler
  transform:
      - type: BaseSilCuttingTransform
        cutting: 10